server:
# 指定端口
  port: 6088

spring:
  application:
    name: limon-server
  mvc:
    pathmatch:
      # Boot 2.6+ 默认的路由匹配策略，Swagger 暂不兼容，使用老策略
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/limon?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root



logging:
  level:
    com.aircjm: DEBUG

knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: "测试"


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath*:/mapper/**/*.xml
