spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/limon?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  redis:
    host: localhost
    port: 6379
    password: root
    database: 5
    timeout: 20000
    pool:
        # 连接池最大连接数（使用负值表示没有限制）
        maxactive: 64
        # 连接池中的最大空闲连接
        maxidle: 64
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        maxwait: 20000
        # 连接池中的最小空闲连接
        minidle: 1
