
# 开发环境配置
server:
    # 服务器的HTTP端口，默认为8085
    port: 8085
    servlet:
        # 应用的访问路径
        context-path: /
    tomcat:
        # tomcat的URI编码
        uri-encoding: UTF-8
        # tomcat最大线程数，默认为200
        max-threads: 800
        # Tomcat启动初始化的线程数，默认值25
        min-spare-threads: 30

# 日志配置
logging:
    level:
        com.aircjm: debug
        org.springframework: warn

# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌秘钥
    secret: abcdefghijklmnopqrstuvwxyzLIMON
    # 令牌有效期（单位/分钟）
    expireTime: 6000

# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.aircjm.project.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    #    mapperLocations: classpath*:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

mybatis-plus:
    global-config:
        db-config:
            id-type: auto
            logic-delete-field: flag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
            logic-delete-value: 1 # 逻辑已删除值(默认为 1)
            logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    mapper-locations: classpath*:mybatis/**/*Mapper.xml

oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI4G2nebsvMQEiFfcXrqmo
    accessKeySecret: UjFSzAz2NX7X1j1snGcvLckERLUW
    bucketName: mingdrive
    filePath: dash/

# Swagger配置
swagger:
    # 是否开启swagger
    enabled: true
    # 请求前缀
    pathMapping: /dev-api

# 防止XSS攻击
xss:
    # 过滤开关
    enabled: true
    # 排除链接（多个用逗号分隔）
    excludes: /system/notice/*
    # 匹配链接
    urlPatterns: /system/*,/monitor/*,/tool/*

# 代码生成
gen:
    # 作者
    author: aircjm
    # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
    packageName: com.aircjm.project.system
    # 自动去除表前缀，默认是true
    autoRemovePre: false
    # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
    tablePrefix: sys_

# 项目相关配置
aircjm:
    # 名称
    name: Limon
    # 版本
    # 版权年份
    versionx    copyrightYear: 2020
    # 实例演示开关
    demoEnabled: true
    # 文件路径 示例（ Windows配置D:/aircjm/uploadPath，Linux配置 /home/aircjm/uploadPath）
    profile: /home/aircjm/uploadPath
    # 获取ip地址开关
    addressEnabled: false

# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://db.limon.com:3306/limon_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: dev
                password: 123456
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url:
                username:
                password:
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter:
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username:
                login-password:
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

    # redis 配置
    redis:
        # 地址
        host: localhost
        # 端口，默认为6379
        port: 6379
        # 密码
        password:
        # 连接超时时间
        timeout: 10s
        lettuce:
            pool:
                # 连接池中的最小空闲连接
                min-idle: 0
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池的最大数据库连接数
                max-active: 8
                # #连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms
    # 资源信息
    messages:
        # 国际化资源文件路径
        basename: i18n/messages
    # 文件上传
    servlet:
        multipart:
            # 单个文件大小
            max-file-size:  10MB
            # 设置总上传的文件大小
            max-request-size:  20MB
